

import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author ChayOMG
 */
public class PantallaCelular extends javax.swing.JFrame {

    
    public PantallaCelular() {
        initComponents();
        setLocationRelativeTo(null);
        
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30); 
        AWTUtilities.setWindowShape(this, forma); 
        
        this.msj.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
        this.pantallaLlamada.setVisible(false);
        this.home.setVisible(false);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(false);
        this.llamada.setVisible(false);
        this.jTextField1.setVisible(false);
        this.asterisco.setVisible(false);
        this.gato.setVisible(false);
        this.cero.setVisible(false);
        this.uno.setVisible(false);
        this.dos.setVisible(false);
        this.tres.setVisible(false);
        this.cuatro.setVisible(false);
        this.cinco.setVisible(false);
        this.seis.setVisible(false);
        this.siete.setVisible(false);
        this.ocho.setVisible(false);
        this.nueve.setVisible(false);
        
        ImageIcon imgIcon3 = new ImageIcon(getClass().getResource("/img/llamadaios.jpg"));
        Image imgEscalada3 = imgIcon3.getImage().getScaledInstance(llamada.getWidth(),
        llamada.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado3 = new ImageIcon(imgEscalada3);
        llamada.setIcon(iconoEscalado3);
        
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/img/menuios.jpg"));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(menuios.getWidth(),
        menuios.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        menuios.setIcon(iconoEscalado);
        
        ImageIcon imgIcon4 = new ImageIcon(getClass().getResource("/img/llamando.jpg"));
        Image imgEscalada4 = imgIcon4.getImage().getScaledInstance(pantallaLlamada.getWidth(),
        pantallaLlamada.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado4 = new ImageIcon(imgEscalada4);
        pantallaLlamada.setIcon(iconoEscalado4);
        
        ImageIcon imgIcon2 = new ImageIcon(getClass().getResource("/img/lock.jpg"));
        Image imgEscalada2 = imgIcon2.getImage().getScaledInstance(equipo.getWidth(),
        lockscreen.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado2 = new ImageIcon(imgEscalada2);
        lockscreen.setIcon(iconoEscalado2);
        
        ImageIcon imgIcon5 = new ImageIcon(getClass().getResource("/img/tecladonume.jpg"));
        Image imgEscalada5 = imgIcon5.getImage().getScaledInstance(pantallaLlamadaTeclado.getWidth(),
        pantallaLlamadaTeclado.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado5 = new ImageIcon(imgEscalada5);
        pantallaLlamadaTeclado.setIcon(iconoEscalado5);

    }
    
    boolean conexion = false;
    String numero = "9981542191";
    String numero2= "9981347477";
    int esfinal=-1, menuopciones=9;
   int enviando=0; 
   int esinicio=0;
   Conexion c= new Conexion();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        msj = new javax.swing.JLabel();
        cancel = new javax.swing.JLabel();
        nueves = new javax.swing.JLabel();
        ochos = new javax.swing.JLabel();
        sietes = new javax.swing.JLabel();
        seiss = new javax.swing.JLabel();
        cincos = new javax.swing.JLabel();
        cuatros = new javax.swing.JLabel();
        tress = new javax.swing.JLabel();
        doss = new javax.swing.JLabel();
        unos = new javax.swing.JLabel();
        cero1 = new javax.swing.JLabel();
        botonteclado = new javax.swing.JLabel();
        colgar = new javax.swing.JLabel();
        pantallaLlamadaTeclado = new javax.swing.JLabel();
        pantallaLlamada = new javax.swing.JLabel();
        llamar = new javax.swing.JLabel();
        gato = new javax.swing.JLabel();
        cero = new javax.swing.JLabel();
        asterisco = new javax.swing.JLabel();
        nueve = new javax.swing.JLabel();
        ocho = new javax.swing.JLabel();
        siete = new javax.swing.JLabel();
        seis = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        cuatro = new javax.swing.JLabel();
        tres = new javax.swing.JLabel();
        dos = new javax.swing.JLabel();
        uno = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        llamada = new javax.swing.JLabel();
        menullamada = new javax.swing.JLabel();
        menuios = new javax.swing.JLabel();
        lockscreen = new javax.swing.JLabel();
        unlock = new javax.swing.JLabel();
        equipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(303, 636));
        jPanel1.setPreferredSize(new java.awt.Dimension(303, 636));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 240, 40));

        msj.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                msjMouseClicked(evt);
            }
        });
        jPanel1.add(msj, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 50, 60));

        cancel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cancelMouseClicked(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 514, 60, 20));

        nueves.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nueves.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nuevesMouseClicked(evt);
            }
        });
        jPanel1.add(nueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 370, 40, 40));

        ochos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ochos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ochosMouseClicked(evt);
            }
        });
        jPanel1.add(ochos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 40, 40));

        sietes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sietes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sietesMouseClicked(evt);
            }
        });
        jPanel1.add(sietes, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 40, 40));

        seiss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seiss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seissMouseClicked(evt);
            }
        });
        jPanel1.add(seiss, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 40, 40));

        cincos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cincos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincosMouseClicked(evt);
            }
        });
        jPanel1.add(cincos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 40, 40));

        cuatros.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuatrosMouseClicked(evt);
            }
        });
        jPanel1.add(cuatros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 40, 40));

        tress.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tressMouseClicked(evt);
            }
        });
        jPanel1.add(tress, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 40, 40));

        doss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        doss.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dossMouseClicked(evt);
            }
        });
        jPanel1.add(doss, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 40, 40));

        unos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        unos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unosMouseClicked(evt);
            }
        });
        jPanel1.add(unos, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 40, 40));

        cero1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cero1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cero1MouseClicked(evt);
            }
        });
        jPanel1.add(cero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 440, 40, 40));

        botonteclado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botonteclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                botontecladoMouseClicked(evt);
            }
        });
        jPanel1.add(botonteclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 60, 70));

        colgar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colgar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colgarMouseClicked(evt);
            }
        });
        jPanel1.add(colgar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 40, 40));

        pantallaLlamadaTeclado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/10572228_666797956743121_7305825_n.jpg"))); // NOI18N
        pantallaLlamadaTeclado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pantallaLlamadaTeclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pantallaLlamadaTecladoMouseClicked(evt);
            }
        });
        jPanel1.add(pantallaLlamadaTeclado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 460));

        pantallaLlamada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(pantallaLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 460));

        llamar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llamarMouseClicked(evt);
            }
        });
        jPanel1.add(llamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 40, 40));

        gato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gatoMouseClicked(evt);
            }
        });
        jPanel1.add(gato, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 40, 40));

        cero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceroMouseClicked(evt);
            }
        });
        jPanel1.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 40, 40));

        asterisco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asterisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asteriscoMouseClicked(evt);
            }
        });
        jPanel1.add(asterisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 40, 40));

        nueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nueveMouseClicked(evt);
            }
        });
        jPanel1.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 40, 40));

        ocho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ochoMouseClicked(evt);
            }
        });
        jPanel1.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 40, 40));

        siete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sieteMouseClicked(evt);
            }
        });
        jPanel1.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, 40));

        seis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seisMouseClicked(evt);
            }
        });
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 40, 40));

        cinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 40, 40));

        cuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuatroMouseClicked(evt);
            }
        });
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 40));

        tres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tresMouseClicked(evt);
            }
        });
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 40, 40));

        dos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dosMouseClicked(evt);
            }
        });
        jPanel1.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 40, 40));

        uno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unoMouseClicked(evt);
            }
        });
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 40, 40));

        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 50, 40));
        jPanel1.add(llamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 460));

        menullamada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menullamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menullamadaMouseClicked(evt);
            }
        });
        jPanel1.add(menullamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 50, 50));
        jPanel1.add(menuios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 460));
        jPanel1.add(lockscreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 460));

        unlock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        unlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unlockMouseEntered(evt);
            }
        });
        jPanel1.add(unlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 250, 50));

        equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone.png"))); // NOI18N
        jPanel1.add(equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 303, 636));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menullamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menullamadaMouseClicked
        // TODO add your handling code here:
        this.menullamada.setVisible(false);
        this.llamada.setVisible(true);
        this.jTextField1.setVisible(true);
        this.msj.setVisible(false);
        this.asterisco.setVisible(true);
        this.gato.setVisible(true);
        this.cero.setVisible(true);
        this.uno.setVisible(true);
        this.dos.setVisible(true);
        this.tres.setVisible(true);
        this.cuatro.setVisible(true);
        this.cinco.setVisible(true);
        this.seis.setVisible(true);
        this.siete.setVisible(true);
        this.ocho.setVisible(true);
        this.nueve.setVisible(true);
        this.cero1.setVisible(false);
        this.unos.setVisible(false);
        this.doss.setVisible(false);
        this.tress.setVisible(false);
        this.cuatros.setVisible(false);
        this.cincos.setVisible(false);
        this.seiss.setVisible(false);
        this.sietes.setVisible(false);
        this.ochos.setVisible(false);
        this.nueves.setVisible(false);
        this.menullamada.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
        this.colgar.setVisible(false);
    }//GEN-LAST:event_menullamadaMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        
        this.menuios.setVisible(true);
        this.llamada.setVisible(false);
        this.menullamada.setVisible(true);
        this.msj.setVisible(true);
        this.colgar.setVisible(false);
        this.pantallaLlamada.setVisible(false);
        this.llamada.setVisible(false);
        this.jTextField1.setVisible(false);
        this.asterisco.setVisible(false);
        this.gato.setVisible(false);
        this.cero.setVisible(false);
        this.uno.setVisible(false);
        this.dos.setVisible(false);
        this.tres.setVisible(false);
        this.cuatro.setVisible(false);
        this.cinco.setVisible(false);
        this.seis.setVisible(false);
        this.siete.setVisible(false);
        this.ocho.setVisible(false);
        this.nueve.setVisible(false);
        this.cero1.setVisible(false);
        this.unos.setVisible(false);
        this.doss.setVisible(false);
        this.tress.setVisible(false);
        this.cuatros.setVisible(false);
        this.cincos.setVisible(false);
        this.seiss.setVisible(false);
        this.sietes.setVisible(false);
        this.ochos.setVisible(false);
        this.nueves.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void unoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"1");
    }//GEN-LAST:event_unoMouseClicked

    private void dosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"2");
    }//GEN-LAST:event_dosMouseClicked

    private void tresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"3");
    }//GEN-LAST:event_tresMouseClicked

    private void cuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"4");
    }//GEN-LAST:event_cuatroMouseClicked

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"5");
    }//GEN-LAST:event_cincoMouseClicked

    private void seisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"6");
    }//GEN-LAST:event_seisMouseClicked

    private void sieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"7");
    }//GEN-LAST:event_sieteMouseClicked

    private void ochoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"8");
        
    }//GEN-LAST:event_ochoMouseClicked

    private void nueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nueveMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"9");
       
    }//GEN-LAST:event_nueveMouseClicked

    private void asteriscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asteriscoMouseClicked
        // TODO add your handling code here:
        if(conexion==true)
            LeeTexto.Lee("Opcion no valida");
        
    }//GEN-LAST:event_asteriscoMouseClicked

    private void ceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceroMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"0");
        else
            LeeTexto.Lee("Opcion no valida");

    }//GEN-LAST:event_ceroMouseClicked

    private void gatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gatoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"#");
        else
            LeeTexto.Lee("Opcion no valida");
    }//GEN-LAST:event_gatoMouseClicked

    private void unlockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unlockMouseEntered
        // TODO add your handling code here:
        this.unlock.setVisible(false);
        this.lockscreen.setVisible(false);
        this.menuios.setVisible(true);
        this.menullamada.setVisible(true);
        this.home.setVisible(true);
        this.jTextField1.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
        this.msj.setVisible(false);
    }//GEN-LAST:event_unlockMouseEntered

    private void llamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llamarMouseClicked
        // TODO add your handling code here:
        //Ahora se supone que cuando" llame al servidor" invocare a la clase conectar
        //Primero creamos el objeto de dicha clase (osease el que nos da acceso a esa clase). Le llamaremos "c"
        
        this.home.setVisible(false);
        this.msj.setVisible(false);
                this.colgar.setVisible(true);
                this.pantallaLlamada.setVisible(true);
                this.menuios.setVisible(false);
                this.menullamada.setVisible(false);
                this.llamada.setVisible(false);
                this.jTextField1.setBackground(Color.BLACK);
                this.jTextField1.setForeground(Color.WHITE);
                this.asterisco.setVisible(false);
                this.gato.setVisible(false);
                this.cero.setVisible(false);
                this.uno.setVisible(false);
                this.dos.setVisible(false);
                this.tres.setVisible(false);
                this.cuatro.setVisible(false);
                this.cinco.setVisible(false);
                this.seis.setVisible(false);
                this.siete.setVisible(false);
                this.ocho.setVisible(false);
                this.nueve.setVisible(false);
                this.cero1.setVisible(false);
                this.unos.setVisible(false);
                this.doss.setVisible(false);
                this.tress.setVisible(false);
                this.cuatros.setVisible(false);
                this.cincos.setVisible(false);
                this.seiss.setVisible(false);
                this.sietes.setVisible(false);
                this.ochos.setVisible(false);
                this.nueves.setVisible(false);
                this.pantallaLlamadaTeclado.setVisible(false);
                this.botonteclado.setVisible(true);
        
        
        
         if(jTextField1.getText().equals(numero) || jTextField1.getText().equals(numero2))
         {
                LeeTexto.Lee("Llamando.");
                variables.numeroingr=jTextField1.getText();
                conexion= c.conectar();
                esinicio=variables.menuinicial;
                if(conexion==false)
                {LeeTexto.Lee("Lo sentimos El numero que usted marco no esta disponible.");
                        LeeTexto.Lee("Adios!");
        conexion=false;
        esinicio=esfinal=0;
        this.msj.setVisible(false);
        this.home.setVisible(false);
        this.pantallaLlamada.setVisible(false);
        this.colgar.setVisible(false);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(true);
        this.llamada.setVisible(true);
        this.jTextField1.setVisible(true);
        this.jTextField1.setBackground(Color.WHITE);
        this.jTextField1.setForeground(Color.BLACK);
        this.asterisco.setVisible(true);
        this.gato.setVisible(true);
        this.cero.setVisible(true);
        this.uno.setVisible(true);
        this.dos.setVisible(true);
        this.tres.setVisible(true);
        this.cuatro.setVisible(true);
        this.cinco.setVisible(true);
        this.seis.setVisible(true);
        this.siete.setVisible(true);
        this.ocho.setVisible(true);
        this.nueve.setVisible(true);
        this.cero1.setVisible(false);
        this.unos.setVisible(false);
        this.doss.setVisible(false);
        this.tress.setVisible(false);
        this.cuatros.setVisible(false);
        this.cincos.setVisible(false);
        this.seiss.setVisible(false);
        this.sietes.setVisible(false);
        this.ochos.setVisible(false);
        this.nueves.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
        

                }
         }
         
         
         
         else 
         {
             LeeTexto.Lee("Error de llamada !, Numero Incorrecto");
            this.home.setVisible(true);
            this.pantallaLlamada.setVisible(false);
            this.colgar.setVisible(false);
            this.menuios.setVisible(false);
            this.menullamada.setVisible(true);
            this.llamada.setVisible(true);
            this.jTextField1.setVisible(true);
            this.jTextField1.setBackground(Color.WHITE);
            this.jTextField1.setForeground(Color.BLACK);
            this.asterisco.setVisible(true);
            this.gato.setVisible(true);
            this.cero.setVisible(true);
            this.uno.setVisible(true);
            this.dos.setVisible(true);
            this.tres.setVisible(true);
            this.cuatro.setVisible(true);
            this.cinco.setVisible(true);
            this.seis.setVisible(true);
            this.siete.setVisible(true);
            this.ocho.setVisible(true);
            this.nueve.setVisible(true);
            this.cero1.setVisible(false);
            this.unos.setVisible(false);
            this.doss.setVisible(false);
            this.tress.setVisible(false);
            this.cuatros.setVisible(false);
            this.cincos.setVisible(false);
            this.seiss.setVisible(false);
            this.sietes.setVisible(false);
            this.ochos.setVisible(false);
            this.nueves.setVisible(false);
            this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
         }
    }//GEN-LAST:event_llamarMouseClicked

    private void colgarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colgarMouseClicked
        // TODO add your handling code here:
        LeeTexto.Lee("Adios!");
        conexion=false;
        esinicio=esfinal=0;
        this.msj.setVisible(false);
        this.home.setVisible(false);
        this.pantallaLlamada.setVisible(false);
        this.colgar.setVisible(false);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(true);
        this.llamada.setVisible(true);
        this.jTextField1.setVisible(true);
        this.jTextField1.setBackground(Color.WHITE);
        this.jTextField1.setForeground(Color.BLACK);
        this.asterisco.setVisible(true);
        this.gato.setVisible(true);
        this.cero.setVisible(true);
        this.uno.setVisible(true);
        this.dos.setVisible(true);
        this.tres.setVisible(true);
        this.cuatro.setVisible(true);
        this.cinco.setVisible(true);
        this.seis.setVisible(true);
        this.siete.setVisible(true);
        this.ocho.setVisible(true);
        this.nueve.setVisible(true);
        this.cero1.setVisible(false);
        this.unos.setVisible(false);
        this.doss.setVisible(false);
        this.tress.setVisible(false);
        this.cuatros.setVisible(false);
        this.cincos.setVisible(false);
        this.seiss.setVisible(false);
        this.sietes.setVisible(false);
        this.ochos.setVisible(false);
        this.nueves.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
        
    }//GEN-LAST:event_colgarMouseClicked

    private void botontecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botontecladoMouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        
        this.pantallaLlamada.setVisible(false);
        this.msj.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(true);
        this.home.setVisible(true);
        this.pantallaLlamada.setVisible(false);
        this.colgar.setVisible(false);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(false);
        this.llamada.setVisible(false);
        this.botonteclado.setVisible(false);
        
        this.jTextField1.setVisible(true);
        this.jTextField1.setBackground(Color.WHITE);
        this.jTextField1.setForeground(Color.BLACK);
        this.asterisco.setVisible(false);
        this.gato.setVisible(false);
        this.cero.setVisible(false);
        this.uno.setVisible(false);
        this.dos.setVisible(false);
        this.tres.setVisible(false);
        this.cuatro.setVisible(false);
        this.cinco.setVisible(false);
        this.seis.setVisible(false);
        this.siete.setVisible(false);
        this.ocho.setVisible(false);
        this.nueve.setVisible(false);
        this.cero1.setVisible(true);
        this.unos.setVisible(true);
        this.doss.setVisible(true);
        this.tress.setVisible(true);
        this.cuatros.setVisible(true);
        this.cincos.setVisible(true);
        this.seiss.setVisible(true);
        this.sietes.setVisible(true);
        this.ochos.setVisible(true);
        this.nueves.setVisible(true);
        this.cancel.setVisible(true);
        this.lockscreen.setVisible(false);
        this.unlock.setVisible(false);
    }//GEN-LAST:event_botontecladoMouseClicked

    private void cancelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cancelMouseClicked
        // TODO add your handling code here:
        
        this.pantallaLlamada.setVisible(true);
        this.msj.setVisible(false);
        this.cero1.setVisible(false);
        this.unos.setVisible(false);
        this.doss.setVisible(false);
        this.tress.setVisible(false);
        this.cuatros.setVisible(false);
        this.cincos.setVisible(false);
        this.seiss.setVisible(false);
        this.sietes.setVisible(false);
        this.ochos.setVisible(false);
        this.nueves.setVisible(false);
        
        this.jTextField1.setVisible(true);
        this.jTextField1.setBackground(Color.WHITE);
        this.jTextField1.setForeground(Color.BLACK);
        this.asterisco.setVisible(false);
        this.gato.setVisible(false);
        this.cero.setVisible(false);
        this.uno.setVisible(false);
        this.dos.setVisible(false);
        this.tres.setVisible(false);
        this.cuatro.setVisible(false);
        this.cinco.setVisible(false);
        this.seis.setVisible(false);
        this.siete.setVisible(false);
        this.ocho.setVisible(false);
        this.nueve.setVisible(false);
        this.home.setVisible(false);
        
        this.llamada.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.home.setVisible(true);
        this.colgar.setVisible(true);
    }//GEN-LAST:event_cancelMouseClicked

    private void cero1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cero1MouseClicked
        // TODO add your handling code here:
//        if (variables.numeroingr==numero)
//        {
        if(conexion!=true)
        {
        jTextField1.setText(jTextField1.getText()+"0");
        variables.menu= jTextField1.getText() + "0";
        }
        
//        }
    }//GEN-LAST:event_cero1MouseClicked

    private void unosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unosMouseClicked
        // TODO add your handling code here:

        if(conexion==true&&enviando==0)
        {
        enviando=1;
            
            int opciones;
           
           if(esinicio!=0&&1<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }
            
            
           else if(esfinal==-1&&1<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else if(esfinal==0)
           {
               variables.comentario=JOptionPane.showInputDialog("Comentarios opcionales: ");
               c.conectarfin(variables.nombre, variables.contacto, variables.comentario, "Resuelto");
               LeeTexto.Lee("Adios!");
        conexion=false;
        this.msj.setVisible(false);
        this.home.setVisible(false);
        this.pantallaLlamada.setVisible(false);
        this.colgar.setVisible(false);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(true);
        this.llamada.setVisible(true);
        this.jTextField1.setVisible(true);
        this.jTextField1.setBackground(Color.WHITE);
        this.jTextField1.setForeground(Color.BLACK);
        this.asterisco.setVisible(true);
        this.gato.setVisible(true);
        this.cero.setVisible(true);
        this.uno.setVisible(true);
        this.dos.setVisible(true);
        this.tres.setVisible(true);
        this.cuatro.setVisible(true);
        this.cinco.setVisible(true);
        this.seis.setVisible(true);
        this.siete.setVisible(true);
        this.ocho.setVisible(true);
        this.nueve.setVisible(true);
        this.cero1.setVisible(false);
        this.unos.setVisible(false);
        this.doss.setVisible(false);
        this.tress.setVisible(false);
        this.cuatros.setVisible(false);
        this.cincos.setVisible(false);
        this.seiss.setVisible(false);
        this.sietes.setVisible(false);
        this.ochos.setVisible(false);
        this.nueves.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
        
               
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
           enviando=0;
         
        }
           
         

    }//GEN-LAST:event_unosMouseClicked

    private void dossMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dossMouseClicked
        // TODO add your handling code here:
//        if (variables.numeroingr==numero)
//        {
             if(conexion==true&&enviando==0)
             {
            enviando=1;
            
            int opciones;
           
           if(esinicio!=0&&2<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }
           else if(esfinal==-1&&2<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else if(esfinal==0)
           {
               variables.comentario=JOptionPane.showInputDialog("Comentarios opcionales: ");
               c.conectarfin(variables.nombre, variables.contacto, variables.comentario, "No resuleto");
               LeeTexto.Lee("Adios!");
        conexion=false;
        this.msj.setVisible(false);
        this.home.setVisible(false);
        this.pantallaLlamada.setVisible(false);
        this.colgar.setVisible(false);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(true);
        this.llamada.setVisible(true);
        this.jTextField1.setVisible(true);
        this.jTextField1.setBackground(Color.WHITE);
        this.jTextField1.setForeground(Color.BLACK);
        this.asterisco.setVisible(true);
        this.gato.setVisible(true);
        this.cero.setVisible(true);
        this.uno.setVisible(true);
        this.dos.setVisible(true);
        this.tres.setVisible(true);
        this.cuatro.setVisible(true);
        this.cinco.setVisible(true);
        this.seis.setVisible(true);
        this.siete.setVisible(true);
        this.ocho.setVisible(true);
        this.nueve.setVisible(true);
        this.cero1.setVisible(false);
        this.unos.setVisible(false);
        this.doss.setVisible(false);
        this.tress.setVisible(false);
        this.cuatros.setVisible(false);
        this.cincos.setVisible(false);
        this.seiss.setVisible(false);
        this.sietes.setVisible(false);
        this.ochos.setVisible(false);
        this.nueves.setVisible(false);
        this.pantallaLlamadaTeclado.setVisible(false);
        this.botonteclado.setVisible(false);
        
               
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
           enviando=0;
         
        }
           

//        }
    }//GEN-LAST:event_dossMouseClicked

    private void tressMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tressMouseClicked
        // TODO add your handling code here:

                if(conexion==true&&enviando==0)
        {
        
            enviando=1;
            int opciones;
           
           if(esinicio!=0&&3<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }
            else    if(esfinal==-1&&3<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
           enviando=0;
         
        }
           

//        }
    }//GEN-LAST:event_tressMouseClicked

    private void cuatrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatrosMouseClicked
        // TODO add your handling code here:
//        if (variables.numeroingr==numero)
        if(conexion==true&&enviando==0)
        {
        enviando=1;
            
            int opciones;
           
           if(esinicio!=0&&3<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }
            else if(esfinal==-1&&4<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
         enviando=0;
        }
           

//        }
    }//GEN-LAST:event_cuatrosMouseClicked

    private void cincosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincosMouseClicked
        // TODO add your handling code here:
//        if (variables.numeroingr==numero)
            if(conexion==true&&enviando ==0)
            {
        enviando=1;
            
            int opciones;
           
           if(esinicio!=0&&5<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }
           else if(esfinal==-1&&5<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
         enviando=0;
        }
//        }
    }//GEN-LAST:event_cincosMouseClicked

    private void seissMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seissMouseClicked
        // TODO add your handling code here:

       if(conexion==true&&enviando==0)
        {
            enviando=1;
            int opciones;
           
           if(esinicio!=0&&6<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }
           else if(esfinal==-1&&6<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
         enviando=0;
        }
//        }
    }//GEN-LAST:event_seissMouseClicked

    private void sietesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sietesMouseClicked
        // TODO add your handling code here:
//        if (variables.numeroingr==numero)
//        {
          if(conexion==true&&enviando==0)
        {
            enviando=1;
            int opciones;
           
           if(esinicio!=0&&7<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }
           else if(esfinal==-1&&7<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
         enviando=0;
        }
//        }
    }//GEN-LAST:event_sietesMouseClicked

    private void ochosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochosMouseClicked
        // TODO add your handling code here:
              if(conexion==true&&enviando==0)
        {
        
            enviando=1;
            int opciones;
           
           if(esinicio!=0&&8<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }
           else if(esfinal==-1&&8<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
           enviando=0;
         
        }

    }//GEN-LAST:event_ochosMouseClicked

    private void nuevesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nuevesMouseClicked
        // TODO add your handling code here:

      if(conexion==true&&enviando==0)
        {
        
            enviando=1;
            int opciones;
         
           if(esinicio!=0&&9<=esinicio)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
               
           }  
           else if(esfinal==-1&&9<menuopciones)
           {
               variables.menu=variables.menu+1;
               opciones=c.mensajeconexion(variables.menu);
               menuopciones=opciones;
               if(opciones==0)
               {
                   esfinal=menuopciones=0;
                   LeeTexto.Lee("Gracias por utilizar nuestro servicio. ¿Le hemos resuelto su duda?. Si. marque 1. No maruqe 2");               
               }
           }
           else
           {
               LeeTexto.Lee("Opcion no valida.");               
           }
         enviando=0;
        }
    }//GEN-LAST:event_nuevesMouseClicked

    private void msjMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_msjMouseClicked
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, variables.menu);
    }//GEN-LAST:event_msjMouseClicked

    private void pantallaLlamadaTecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pantallaLlamadaTecladoMouseClicked
        // TODO add your handling code here:
        this.home.setVisible(false);
    }//GEN-LAST:event_pantallaLlamadaTecladoMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCelular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asterisco;
    private javax.swing.JLabel botonteclado;
    private javax.swing.JLabel cancel;
    private javax.swing.JLabel cero;
    private javax.swing.JLabel cero1;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel cincos;
    private javax.swing.JLabel colgar;
    private javax.swing.JLabel cuatro;
    private javax.swing.JLabel cuatros;
    private javax.swing.JLabel dos;
    private javax.swing.JLabel doss;
    private javax.swing.JLabel equipo;
    private javax.swing.JLabel gato;
    private javax.swing.JLabel home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel llamada;
    private javax.swing.JLabel llamar;
    private javax.swing.JLabel lockscreen;
    private javax.swing.JLabel menuios;
    private javax.swing.JLabel menullamada;
    private javax.swing.JLabel msj;
    private javax.swing.JLabel nueve;
    private javax.swing.JLabel nueves;
    private javax.swing.JLabel ocho;
    private javax.swing.JLabel ochos;
    private javax.swing.JLabel pantallaLlamada;
    private javax.swing.JLabel pantallaLlamadaTeclado;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel seiss;
    private javax.swing.JLabel siete;
    private javax.swing.JLabel sietes;
    private javax.swing.JLabel tres;
    private javax.swing.JLabel tress;
    private javax.swing.JLabel unlock;
    private javax.swing.JLabel uno;
    private javax.swing.JLabel unos;
    // End of variables declaration//GEN-END:variables
}
