
import com.sun.awt.AWTUtilities;
import java.awt.Color;
import java.awt.Image;
import java.awt.Shape;
import java.awt.geom.RoundRectangle2D;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ChayOMG
 */
public class PantallaCelular extends javax.swing.JFrame {

    /**
     * Creates new form PantallaAndroid
     */
    public PantallaCelular() {
        initComponents();
        setLocationRelativeTo(null);
        
        Shape forma = new RoundRectangle2D.Double(0, 0, this.getBounds().width, this.getBounds().height, 30, 30); 
        AWTUtilities.setWindowShape(this, forma); 
        
        this.pantallaLlamada.setVisible(false);
        this.home.setVisible(false);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(false);
        this.llamada.setVisible(false);
        this.jTextField1.setVisible(false);
        this.asterisco.setVisible(false);
        this.gato.setVisible(false);
        this.cero.setVisible(false);
        this.uno.setVisible(false);
        this.dos.setVisible(false);
        this.tres.setVisible(false);
        this.cuatro.setVisible(false);
        this.cinco.setVisible(false);
        this.seis.setVisible(false);
        this.siete.setVisible(false);
        this.ocho.setVisible(false);
        this.nueve.setVisible(false);
        
        ImageIcon imgIcon3 = new ImageIcon(getClass().getResource("/img/llamadaios.jpg"));
        Image imgEscalada3 = imgIcon3.getImage().getScaledInstance(llamada.getWidth(),
        llamada.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado3 = new ImageIcon(imgEscalada3);
        llamada.setIcon(iconoEscalado3);
        
        ImageIcon imgIcon = new ImageIcon(getClass().getResource("/img/menuios.jpg"));
        Image imgEscalada = imgIcon.getImage().getScaledInstance(menuios.getWidth(),
        menuios.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado = new ImageIcon(imgEscalada);
        menuios.setIcon(iconoEscalado);
        
        ImageIcon imgIcon4 = new ImageIcon(getClass().getResource("/img/llamando.jpg"));
        Image imgEscalada4 = imgIcon4.getImage().getScaledInstance(pantallaLlamada.getWidth(),
        pantallaLlamada.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado4 = new ImageIcon(imgEscalada4);
        pantallaLlamada.setIcon(iconoEscalado4);
        
        ImageIcon imgIcon2 = new ImageIcon(getClass().getResource("/img/lock.jpg"));
        Image imgEscalada2 = imgIcon2.getImage().getScaledInstance(equipo.getWidth(),
        lockscreen.getHeight(), Image.SCALE_SMOOTH);
        Icon iconoEscalado2 = new ImageIcon(imgEscalada2);
        lockscreen.setIcon(iconoEscalado2);

    }
    
    boolean conexion = false;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        colgar = new javax.swing.JLabel();
        pantallaLlamada = new javax.swing.JLabel();
        llamar = new javax.swing.JLabel();
        gato = new javax.swing.JLabel();
        cero = new javax.swing.JLabel();
        asterisco = new javax.swing.JLabel();
        nueve = new javax.swing.JLabel();
        ocho = new javax.swing.JLabel();
        siete = new javax.swing.JLabel();
        seis = new javax.swing.JLabel();
        cinco = new javax.swing.JLabel();
        cuatro = new javax.swing.JLabel();
        tres = new javax.swing.JLabel();
        dos = new javax.swing.JLabel();
        uno = new javax.swing.JLabel();
        home = new javax.swing.JLabel();
        llamada = new javax.swing.JLabel();
        menullamada = new javax.swing.JLabel();
        menuios = new javax.swing.JLabel();
        lockscreen = new javax.swing.JLabel();
        unlock = new javax.swing.JLabel();
        equipo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setMinimumSize(new java.awt.Dimension(303, 636));
        jPanel1.setPreferredSize(new java.awt.Dimension(303, 636));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 250, 60));

        colgar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colgar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colgarMouseClicked(evt);
            }
        });
        jPanel1.add(colgar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 40, 40));

        pantallaLlamada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(pantallaLlamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 460));

        llamar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        llamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                llamarMouseClicked(evt);
            }
        });
        jPanel1.add(llamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, 40, 40));

        gato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        gato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gatoMouseClicked(evt);
            }
        });
        jPanel1.add(gato, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 40, 40));

        cero.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cero.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ceroMouseClicked(evt);
            }
        });
        jPanel1.add(cero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 40, 40));

        asterisco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        asterisco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                asteriscoMouseClicked(evt);
            }
        });
        jPanel1.add(asterisco, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, 40, 40));

        nueve.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        nueve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nueveMouseClicked(evt);
            }
        });
        jPanel1.add(nueve, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 40, 40));

        ocho.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ocho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ochoMouseClicked(evt);
            }
        });
        jPanel1.add(ocho, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 310, 40, 40));

        siete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        siete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sieteMouseClicked(evt);
            }
        });
        jPanel1.add(siete, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 40, 40));

        seis.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        seis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                seisMouseClicked(evt);
            }
        });
        jPanel1.add(seis, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 40, 40));

        cinco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cinco.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cincoMouseClicked(evt);
            }
        });
        jPanel1.add(cinco, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 40, 40));

        cuatro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cuatro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cuatroMouseClicked(evt);
            }
        });
        jPanel1.add(cuatro, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 40, 40));

        tres.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tresMouseClicked(evt);
            }
        });
        jPanel1.add(tres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 40, 40));

        dos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dosMouseClicked(evt);
            }
        });
        jPanel1.add(dos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 40, 40));

        uno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        uno.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                unoMouseClicked(evt);
            }
        });
        jPanel1.add(uno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 40, 40));

        home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });
        jPanel1.add(home, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 570, 50, 40));
        jPanel1.add(llamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 260, 450));

        menullamada.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        menullamada.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menullamadaMouseClicked(evt);
            }
        });
        jPanel1.add(menullamada, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 50, 50));
        jPanel1.add(menuios, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 460));
        jPanel1.add(lockscreen, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 260, 460));

        unlock.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        unlock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                unlockMouseEntered(evt);
            }
        });
        jPanel1.add(unlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 250, 50));

        equipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/iphone.png"))); // NOI18N
        jPanel1.add(equipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 303, 636));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menullamadaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menullamadaMouseClicked
        // TODO add your handling code here:
        this.menullamada.setVisible(false);
        this.llamada.setVisible(true);
        this.jTextField1.setVisible(true);
        
        this.asterisco.setVisible(true);
        this.gato.setVisible(true);
        this.cero.setVisible(true);
        this.uno.setVisible(true);
        this.dos.setVisible(true);
        this.tres.setVisible(true);
        this.cuatro.setVisible(true);
        this.cinco.setVisible(true);
        this.seis.setVisible(true);
        this.siete.setVisible(true);
        this.ocho.setVisible(true);
        this.nueve.setVisible(true);
        this.menullamada.setVisible(false);
    }//GEN-LAST:event_menullamadaMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        // TODO add your handling code here:
        jTextField1.setText("");
        
        this.menuios.setVisible(true);
        this.llamada.setVisible(false);
        this.menullamada.setVisible(true);
        
        this.colgar.setVisible(false);
        this.pantallaLlamada.setVisible(false);
        this.llamada.setVisible(false);
        this.jTextField1.setVisible(false);
        this.asterisco.setVisible(false);
        this.gato.setVisible(false);
        this.cero.setVisible(false);
        this.uno.setVisible(false);
        this.dos.setVisible(false);
        this.tres.setVisible(false);
        this.cuatro.setVisible(false);
        this.cinco.setVisible(false);
        this.seis.setVisible(false);
        this.siete.setVisible(false);
        this.ocho.setVisible(false);
        this.nueve.setVisible(false);
    }//GEN-LAST:event_homeMouseClicked

    private void unoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"1");
        else
        {}
    }//GEN-LAST:event_unoMouseClicked

    private void dosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dosMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"2");
        else
        {}
    }//GEN-LAST:event_dosMouseClicked

    private void tresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tresMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"3");
        else
        {}
    }//GEN-LAST:event_tresMouseClicked

    private void cuatroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cuatroMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"4");
        else
        {}
    }//GEN-LAST:event_cuatroMouseClicked

    private void cincoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cincoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"5");
        else
        {}
    }//GEN-LAST:event_cincoMouseClicked

    private void seisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_seisMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"6");
        else
        {}
    }//GEN-LAST:event_seisMouseClicked

    private void sieteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sieteMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"7");
        else
        {}
    }//GEN-LAST:event_sieteMouseClicked

    private void ochoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ochoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"8");
        else
        {}
    }//GEN-LAST:event_ochoMouseClicked

    private void nueveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nueveMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"9");
        else
        {}
    }//GEN-LAST:event_nueveMouseClicked

    private void asteriscoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_asteriscoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"*");
        else
        {}
    }//GEN-LAST:event_asteriscoMouseClicked

    private void ceroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ceroMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"0");
        else
        {}
    }//GEN-LAST:event_ceroMouseClicked

    private void gatoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gatoMouseClicked
        // TODO add your handling code here:
        if(conexion!=true)
        jTextField1.setText(jTextField1.getText()+"#");
        else
        {}
    }//GEN-LAST:event_gatoMouseClicked

    private void unlockMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_unlockMouseEntered
        // TODO add your handling code here:
        this.unlock.setVisible(false);
        this.lockscreen.setVisible(false);
        this.menuios.setVisible(true);
        this.menullamada.setVisible(true);
        this.home.setVisible(true);
        this.jTextField1.setVisible(false);
    }//GEN-LAST:event_unlockMouseEntered

    private void llamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_llamarMouseClicked
        // TODO add your handling code here:
        this.home.setVisible(true);
        this.colgar.setVisible(true);
        this.pantallaLlamada.setVisible(true);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(false);
        this.llamada.setVisible(false);
        this.jTextField1.setBackground(Color.BLACK);
        this.jTextField1.setForeground(Color.WHITE);
        this.asterisco.setVisible(false);
        this.gato.setVisible(false);
        this.cero.setVisible(false);
        this.uno.setVisible(false);
        this.dos.setVisible(false);
        this.tres.setVisible(false);
        this.cuatro.setVisible(false);
        this.cinco.setVisible(false);
        this.seis.setVisible(false);
        this.siete.setVisible(false);
        this.ocho.setVisible(false);
        this.nueve.setVisible(false);
    }//GEN-LAST:event_llamarMouseClicked

    private void colgarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colgarMouseClicked
        // TODO add your handling code here:
        this.home.setVisible(true);
        this.pantallaLlamada.setVisible(false);
        this.colgar.setVisible(false);
        this.menuios.setVisible(false);
        this.menullamada.setVisible(true);
        this.llamada.setVisible(true);
        this.jTextField1.setVisible(true);
        this.jTextField1.setBackground(Color.WHITE);
        this.jTextField1.setForeground(Color.BLACK);
        this.asterisco.setVisible(true);
        this.gato.setVisible(true);
        this.cero.setVisible(true);
        this.uno.setVisible(true);
        this.dos.setVisible(true);
        this.tres.setVisible(true);
        this.cuatro.setVisible(true);
        this.cinco.setVisible(true);
        this.seis.setVisible(true);
        this.siete.setVisible(true);
        this.ocho.setVisible(true);
        this.nueve.setVisible(true);
    }//GEN-LAST:event_colgarMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaCelular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaCelular().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel asterisco;
    private javax.swing.JLabel cero;
    private javax.swing.JLabel cinco;
    private javax.swing.JLabel colgar;
    private javax.swing.JLabel cuatro;
    private javax.swing.JLabel dos;
    private javax.swing.JLabel equipo;
    private javax.swing.JLabel gato;
    private javax.swing.JLabel home;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel llamada;
    private javax.swing.JLabel llamar;
    private javax.swing.JLabel lockscreen;
    private javax.swing.JLabel menuios;
    private javax.swing.JLabel menullamada;
    private javax.swing.JLabel nueve;
    private javax.swing.JLabel ocho;
    private javax.swing.JLabel pantallaLlamada;
    private javax.swing.JLabel seis;
    private javax.swing.JLabel siete;
    private javax.swing.JLabel tres;
    private javax.swing.JLabel unlock;
    private javax.swing.JLabel uno;
    // End of variables declaration//GEN-END:variables
}
